### ISSUE TITLE
Ajuste na visualização das transações

### ISSUE THREAD

**Issue by Fernnandez** [Fernnandez/Riquinho#22]
eu como dev quero ajustar a visualização das transações do tipo receita ou gastos e exibir esses dados condicionalmente no front e melhorar o código dessa exibição

**Comment by Pedrohsmarinho** [comment]
Os ajustes feitos foram, a troca dos inputs para letra maiúscula, adição da função number formart e mudando o tempo de exposição da mensagem de feedback. Fora isso também foi setado a formatação dos inputs para como vamos usar.
